doxwiki/urls.py
from django.conf.urls import url
from . import views

app_name = 'doxwiki'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^tag/$', views.TagList.as_view(), name='tag_list'),
    url(r'^category/$', views.CategoryList.as_view(), name='category_list'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.tag, name='tag'),
    url(r'^category/(?P<slug>[-\w]+)/$', views.category, name='category'),
    url(r'^(?P<slug>[-\w]+)/$', views.page, name='page'),
    url(r'^(?P<slug>[-\w]+)/(?P<attachment>.*)/$', views.attachment, name='attachment'),
]

doxwiki/models.py
import os
from django.db import models
from django.utils.text import slugify
from .marker import Marker
import datetime

# Create your models here.

class Page(models.Model):
    title = models.CharField(max_length=300) # ADD: lowercase/slug checking
    slug = models.SlugField(max_length=300, unique=True)
    content = models.TextField()
    date_created = models.DateTimeField()
    date_modified = models.DateTimeField()
    tags = models.ManyToManyField('Tag', blank=True)
    categories = models.ManyToManyField('Category', blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.date_modified = datetime.datetime.now()
        super().save(*args, **kwargs)

    @property
    def html(self):
        return Marker().to_html(self.content)

    def __str__(self):
        return "{}".format(self.title)


def page_upload_path(instance, filename):
    return os.path.join('attachments', str(instance.page.id), filename) 


class Attachment(models.Model):
    file = models.FileField(upload_to=page_upload_path)
    page = models.ForeignKey(Page)

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return "{}".format(self.file.name)


class Tag(models.Model):
    name = models.SlugField(unique=True)

    def __str__(self):
        return "{}".format(self.name)


class Category(models.Model):
    name = models.SlugField(unique=True)
    parent = models.ForeignKey('self', models.SET_NULL, null=True, blank=True, related_name='child_set')

    def __str__(self):
        return "{}".format(self.name)

doxwiki/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from . import models
from . import marker

# Create your views here.
def about(req):
    return HttpResponse('This is doxwiki')


def index(req):
    sort_by = req.GET.get('sort', '-date_created')
    pages = models.Page.objects.order_by(sort_by).all()
    context = {'pages': pages}
    return render(req, 'doxwiki/index.html', context)


def page(req, slug):
    page = models.Page.objects.get(slug=slug)
    if not page:
        # prompt to create a page
        pass
    context = {'page': page}
    return render(req, 'doxwiki/page.html', context)


def tag(req, slug):
    tag = get_object_or_404(models.Tag, name=slug)
    context = {'tag': tag}
    return render(req, 'doxwiki/tag.html', context)


def category(req, slug):
    category = get_object_or_404(models.Category, name=slug)
    context = {'category': category}
    return render(req, 'doxwiki/category.html', context)


class TagList(generic.ListView):
    model = models.Tag
    context_object_name = 'tags'


class CategoryList(generic.ListView):
    model = models.Category
    context_object_name = 'categories'


def attachment(req, slug, attachment):
    return HttpResponse('attachment')

doxwiki/templates/doxwiki/add.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='simplemde.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='editor.css')}}">
<script src="{{ url_for('static', filename='simplemde.min.js')}}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='jquery.tag-editor.css') }}">
{% endblock %}
{% block body %}
<h1> Add a new page </h1>
<form method="POST">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="title" class="form-control" id="title" placeholder="Title">
    </div>
    <div class="form-group">
        <label for="cat-tags">Categories</label>
        <input class="form-control" id="cat-tags" name="cat-tags">
    </div>
    <div class="form-group">
        <label for="tagger">Tags</label>
        <input class="form-control" id="tagger">
    </div>
    <div class="form-group">
        <label for="exampleInputFile">File input</label>
        <input type="file" id="exampleInputFile">
        <p class="help-block">Example block-level help text here.</p>
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox"> Check me out
        </label>
    </div>
    <div id="tag-list">
    </div>
    <div id="category-list">
    </div>
    <div class="form-group">
        <label for="Content">Content</label>
        <textarea name="content" id="content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}
{% block script %}
$('#tagger').tagEditor();
$("form").submit( function(eventObj) {
    var tags = $('#tagger').tagEditor('getTags')[0].tags;
    $.each(tags, function(i, v){
        $('<input />').attr('type', 'hidden')
            .attr('name', "tags[]")
            .attr('value', v)
            .appendTo('#tag-list');
    });
    return true;
});

$('#cat-tags').tagEditor();
$("form").submit( function(eventObj) {
    var tags = $('#cat-tags').tagEditor('getTags')[0].tags;
    $.each(tags, function(i, v){
        $('<input />').attr('type', 'hidden')
            .attr('name', "categories[]")
            .attr('value', v)
            .appendTo('#category-list');
    });
    return true;
});
var editor = new SimpleMDE({ element: $("#content")[0] });
{% endblock %}

doxwiki/templates/doxwiki/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>WoxWiki</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'doxwiki/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'doxwiki/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'doxwiki/css/bootflat.css' %}">
        <link rel="stylesheet" href="{% static 'doxwiki/css/custom.css' %}">
        {% block head %}{% endblock %}
        <style>{% block style %}{% endblock %}</style>
    </head>
    <body>
        {% include "doxwiki/navbar.html" %}
        <div class="container">
        <main id="main">
        {% block body %}{% endblock %}
        </main>
        </div>
        <script src="{% static 'doxwiki/js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'doxwiki/js/jquery.caret.min.js' %}"></script>
        <script src="{% static 'doxwiki/js/jquery.tag-editor.min.js' %}"></script>
        <script src="{% static 'doxwiki/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript">{% block script %}{% endblock %}</script>
    </body>
</html>

doxwiki/templates/doxwiki/category.html
{% extends "doxwiki/base.html" %}
{% block body %}
<h1>Pages with the category <strong>{{ category.name }}</strong></h1>
{% if category.page_set %}
<ul>
{% for page in category.page_set.all %}
<li>
    <a href="{% url 'doxwiki:page' page.slug %}">{{page.title}}</a>
    {% if page.categories %}
    {% for category in page.categories.all %}    
    <div class="category-item">{{ category.name }}</div> 
    {% endfor %}
    {% endif %}
</li>
{% endfor %}
</ul>
{% else %}
<div class="alert alert-info">No pages found. Consider adding this category to some of your pages.</div>
{% endif %}
{% endblock %}

doxwiki/templates/doxwiki/category_list.html
{% extends "doxwiki/base.html" %}
{% block body %}
<h1>List of all categories</h1>
{% if categories %}
<div class="table-responsive">
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Category</th>
            <th>Parent</th>
            <th>Children</th>
        </tr>
    </thead>
    <tbody>
{% for category in categories %}
    <tr>
        <td><a href="{% url 'doxwiki:category' category.name %}">{{category.name}}</a></td>
        <td>
            {% if category.parent %}
                <a href="{% url 'doxwiki:category' category.parent.name %}">{{category.parent.name}}</a></td>
            {% else %}
                ---
            {% endif %}
        </td>
        <td>
            {% for child in category.child_set.all %}
                <a href="{% url 'doxwiki:category' child.name %}">{{ child.name }}</a></td>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
</div>
{% else %}
<div class="alert alert-info">No categories found. Consider adding some categories to your pages.</div>
{% endif %}
{% endblock %}

doxwiki/templates/doxwiki/flash_msg.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<ul class=flashes>
    {% for flash_category, flash_message in messages %}
    <li class="alert alert-{{ flash_category }}">{{ flash_message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

doxwiki/templates/doxwiki/index.html
{% extends "doxwiki/base.html" %}
{% block body %}
<h1>Welcome</h1>
<p>Sort by <a href="{% url 'doxwiki:index' %}?sort=-date_modified">Recently modified</a>, <a href="{% url 'doxwiki:index' %}">Newest</a>, <a href="{% url 'doxwiki:index' %}?sort=date_created">Oldest</a></p>
<div class="table-responsive">
<table class="table">
<thead>
    <tr>
        <th>Page</th>
        <th>Filed under</th>
    </tr>
</thead>
<tbody>
{% for page in pages %}
<tr>
    <td><a href="{% url 'doxwiki:page' page.slug %}">{{page.title}}</a></td>
    <td>
    {% if page.categories %}
    {% for category in page.categories.all %}    
    <div class="tag-item"><span class="label label-primary"><a href="{% url 'doxwiki:category' category.name %}">{{ category.name }}</a></span></div>
    {% endfor %}
    {% endif %}
    {% if page.tags %}
    {% for tag in page.tags.all %}    
    <div class="tag-item"><span class="label label-default"><a href="{% url 'doxwiki:tag' tag.name %}">{{ tag.name }}</a></span></div>
    {% endfor %}
    {% endif %}
    </td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

doxwiki/templates/doxwiki/navbar.html
<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'doxwiki:index' %}">WoxWiki</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'doxwiki:category_list' %}">Categories</a></li>
                <li><a href="{% url 'doxwiki:tag_list' %}">Tags</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/add">Add-Page</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

doxwiki/templates/doxwiki/page.html
{% extends "doxwiki/base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'doxwiki/css/simplemde.min.css'%}">
<link rel="stylesheet" href="{% static 'doxwiki/css/editor.css' %}">
<script src="{% static 'doxwiki/js/simplemde.min.js' %}"></script>
{% endblock %}
{% block body %}
<h1>{{ page.title }}</h1>
<p><div> 
{% if page.categories %}
{% for category in page.categories.all %}    
<div class="tag-item"><span class="label label-primary"><a href="{% url 'doxwiki:category' category.name %}">{{ category.name }}</a></span></div>
{% endfor %}
{% endif %}
{% if page.tags %}
{% for tag in page.tags.all %}    
<div class="tag-item"><span class="label label-default"><a href="{% url 'doxwiki:tag' tag.name %}">{{ tag.name }}</a></span></div>
{% endfor %}
{% endif %}
</div>
</p>
<br>
{{ page.html | safe }}
<br>
<div class="panel panel-default">
  <div class="panel-heading">Meta</div>
  <div class="panel-body">
<p>Created on <span class="label label-primary">{{ page.date_created }}</span>
 Modified on <span class="label label-default">{{ page.date_modified }}</span></p>
  </div>

{% if page.attachment_set %}
  <div class="list-group">
      {% for attachment in page.attachment_set.all %}
      <a href="{{ attachment.file.url }}" class="list-group-item"><span class="glyphicon glyphicon-file"></span> {{ attachment.file.name }}</a>
      {% endfor %}
  </div>
{% endif %}
</div>
{% endblock %}

doxwiki/templates/doxwiki/tag.html
{% extends "doxwiki/base.html" %}
{% block body %}
<h1>Pages tagged with <strong>{{ tag.name }}</strong></h1>
{% if tag.page_set %}
<ul>
{% for page in tag.page_set.all %}
<li>
    <a href="{% url 'doxwiki:page' page.id %}">{{page.title}}</a>
    {% if page.tags %}
    {% for tag in page.tags.all %}    
    <div class="tag-item">{{ tag.name }}</div> 
    {% endfor %}
    {% endif %}
</li>
{% endfor %}
</ul>
{% else %}
<div class="alert alert-info">No pages found. Consider adding this tag to some of your pages.</div>
{% endif %}
{% endblock %}

doxwiki/templates/doxwiki/tag_list.html
{% extends "doxwiki/base.html" %}
{% block body %}
<h1>List of all tags</h1>
{% if tags %}
<ul>
{% for tag in tags %}
<li>
    <p><a href="{% url 'doxwiki:tag' tag.name%}">{{tag.name}}</a><p>
</li>
{% endfor %}
</ul>
{% else %}
<div class="alert alert-info">No tags found. Consider adding some tags to your pages.</div>
{% endif %}
{% endblock %}